services:
  - type: web
    name: eld-route-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
    autoDeploy: true
