services:
  # === BACKEND (Django) ===
  - type: web
    name: eld-route-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.13.4
    # Backend root directory (where manage.py is)
    rootDir: .

   # === FRONTEND (React) ===
  - type: web
    name: eld-route-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: REACT_APP_API_URL
        value: https://eld-route-backend.onrender.com
