# Generated by Django 5.2.7 on 2025-10-29 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup', models.CharField(max_length=255)),
                ('dropoff', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField(default=0.0)),
                ('route_geojson', models.JSONField(blank=True, null=True)),
                ('route_summary', models.JSONField(blank=True, null=True)),
                ('eld_logs', models.JSONField(blank=True, null=True)),
                ('exported_pdf', models.FileField(blank=True, null=True, upload_to='eld_pdfs/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
